// Code generated by MockGen. DO NOT EDIT.
// Source: ./comment.go

// Package mock_comment is a generated GoMock package.
package mock_comment

import (
	context "context"
	reflect "reflect"
	mongo0 "task-manager-api/internal/mongo"

	gomock "github.com/golang/mock/gomock"
	mongo "go.mongodb.org/mongo-driver/mongo"
	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MockIMongo is a mock of IMongo interface.
type MockIMongo struct {
	ctrl     *gomock.Controller
	recorder *MockIMongoMockRecorder
}

// MockIMongoMockRecorder is the mock recorder for MockIMongo.
type MockIMongoMockRecorder struct {
	mock *MockIMongo
}

// NewMockIMongo creates a new mock instance.
func NewMockIMongo(ctrl *gomock.Controller) *MockIMongo {
	mock := &MockIMongo{ctrl: ctrl}
	mock.recorder = &MockIMongoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMongo) EXPECT() *MockIMongoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockIMongo) Find(ctx context.Context, filter interface{}, opts ...*options.FindOptions) (mongo0.Cursor, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(mongo0.Cursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIMongoMockRecorder) Find(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIMongo)(nil).Find), varargs...)
}

// InsertOne mocks base method.
func (m *MockIMongo) InsertOne(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, document}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOne", varargs...)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockIMongoMockRecorder) InsertOne(ctx, document interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, document}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockIMongo)(nil).InsertOne), varargs...)
}
