config:
  server:
    port: 3000
    read_timeout: 60
    write_timeout: 60
    shutdown_timeout: 30
  mongodb:
    collection:
      tasks: tasks
    timeout: 60 #second
    default_context_timeout: 60 #second
    app_name: test