version: "3.7"
services:
  database:
    image: mongo:6.0.5
    restart: always
    ports:
      - 27017:27017
    networks:
      - default
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=taskManager
      - MONGO_INITDB_USERNAME=managerapp
      - MONGO_INITDB_PASSWORD=1111
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
  task-manager:
    image: task-manager-api
    build: .
    container_name: task-manager-api
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      - database
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SERVER_TYPE=Production
      - MONGO_HOST=mongodb://database:27017
      - MONGO_DBNAME=taskManager
      - MONGO_USERNAME=managerapp
      - MONGO_PASSWORD=1111
    restart: always

networks:
  default:
    driver: bridge